node {
   def commit_id
   stage('step a') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       dir("basics"){
       sh 'npm install --only=dev'
       sh 'npm test'
       }
     }
   }
   stage('docker build/push') {
      dir("${env.WORKSPACE}/basics"){
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub1') {
          def app = docker.build("yisca/docker-nodejs-demo:latest", '-f Dockerfile .').push()
        }
      }
   }
   stage('docker run') {
     sh label: '', script: ''' 
      docker run --rm -tid --name docker_test -p 3000 yisca/docker-nodejs-demo:latest
      docker kill docker_test
      
      '''
     }
   }

